### ISSUE TITLE
Unable to use the registry with protus

### ISSUE THREAD

**Issue by syedalamabbas** [rancher/community-catalog#106]
Hi,
        I was just trying to get the registry to work on my local host but when I launch it it shows the following error:
`
  Error (500 Server Error: Internal Server Error ("create registry/db: volume name invalid: "registry/db" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed"))`

It always fails to launch the first database container. Has someone used this before ?

**Comment by rawmind0** [comment]
Working correclty in current version...

Please, reopen if you still have the issue.
