### ISSUE TITLE
Jenkins-CI Port Linking

### ISSUE THREAD

**Issue by bjoernwenzel-tommapps** [rancher/community-catalog#107]
Please allow to link Jenkins-CI Container Port to another Port on Host system.
If you run rancher in single node installation the default port for rancher-server is 8080 run in conflict with jenkins-ci

**Comment by eeezyy** [comment]
I saw that there is a preview when starting to create the catalog template for jenkins-ci.
By creating a new Stack under Applications you are able to provide these types of configuration files you where able to see in the preview of the catalog stack.
When you copy and paste the contents to the corresponding files and change the port to e.g. 8081:8080 you can redirect the port and also use the template of the catalog.
Hope I could help.

**Comment by ovidiub13** [comment]
The Jenkins-CI catalog entry has a PORT field. You can just change the port there.
