### ISSUE TITLE
Consul fails to start

### ISSUE THREAD

**Issue by fbrbovic** [rancher/community-catalog#11]
Consul Catalog fails to start, missing husseingalal/consul and husseingalal/consul-config  images @galal-hussein

**Comment by galal-hussein** [comment]
@fbrbovic I think I accidentally turned to the images to private images on Docker Hub, they are public now and should work without problems.

You can find the two repos here: 

- [consul](https://github.com/galal-hussein/consul-rancher)
- [consul-config](https://github.com/galal-hussein/consul-config)

**Comment by cloudnautique** [comment]
Thanks @galal-hussein, closing this issue now.
