### ISSUE TITLE
droneworkers either doesn't work or setup isn't clear enough

### ISSUE THREAD

**Issue by firrae** [rancher/community-catalog#127]
Hey there,

So I was really pumped to see that someone had made a dynamic worker creator, so I set it up and found the setup from the catalogue to be a bit confusing, that's fine, I get it's experimental and new, but I'm not sure what is being asked for in the "Stack name" field. I've tried bot the actual stack name, in my case "drone", and used "drone-server" as it says "should be the same as above". Neither of these seem to work other than to remove ALL workers from the drone server (I'm using the default catalogue one). Am I misunderstanding what these fields are, or is it simply not in a working state?

Thanks!

**Comment by cdaguerre** [comment]
You have to set the exact same name as the one you are creating!
<img width="373" alt="capture d ecran 2016-05-19 a 16 30 42" src="https://cloud.githubusercontent.com/assets/4642448/15397077/0faccd82-1ddf-11e6-8b80-dbad344ed15d.png">

**Comment by rawmind0** [comment]
Please, reopen it you still have the issue.
