### ISSUE TITLE
Janitor template gives error on deploy

### ISSUE THREAD

**Issue by sshipway** [rancher/community-catalog#142]
When deploying a Janitor container (v1.6.0 with the latest Privileged mode option) it gives an error:

Activating (Service 'cleanup' configuration key 'privileged' contains an invalid type, it should be a boolean.)

However looking at the template definition, it seems to be valid.  Is this because of a trailing newline or similar?

**Comment by sshipway** [comment]
Looks like a problem with the Rancher parser?  Possibly it is verifying the YAML before it does variable substitution rather than after.  This is Rancher v1.1.0-dev1

**Comment by sshipway** [comment]
This is logged against Rancher in https://github.com/rancher/rancher/issues/4822

**Comment by rawmind0** [comment]
Current version working.

Please reopen if you still have the issue.
