### ISSUE TITLE
Unable to get secrets-bridge working

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/community-catalog#146]
@cloudnautique I am trying to get the secrets-bridge to work as you showed in the April 2016 online meetup, but am having trouble.  I first started by deploying both server, agent and test alpine container on a single local VM.  Then I tried deploying to a two-environment, 1 host per environment set up with the same results.  

Logs for bridge server:
`5/17/2016 8:51:56 AMtime="2016-05-17T12:51:56Z" level=info msg="Listening on port: 8181"`

Logs for bridge agent:
```
5/17/2016 8:55:19 AMtime="2016-05-17T12:55:19Z" level=info msg="Entering event listening Loop"
5/17/2016 8:56:18 AMtime="2016-05-17T12:56:18Z" level=info msg="Received action: start, from container: c5201eb621f1d707202a9603ab9fc35d37fef7fcb78b8e1355c00570efe80813"

```
Logs for vault server:
```
5/17/2016 7:45:46 AM==> WARNING: Dev mode is enabled!
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AMIn this mode, Vault is completely in-memory and unsealed.
5/17/2016 7:45:46 AMVault is configured to only have a single unseal key. The root
5/17/2016 7:45:46 AMtoken has already been authenticated with the CLI, so you can
5/17/2016 7:45:46 AMimmediately begin using the Vault CLI.
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AMThe only step you need to take is to set the following
5/17/2016 7:45:46 AMenvironment variables:
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: security barrier initialized (shares: 1, threshold 1)
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: post-unseal setup starting
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: mounted backend of type generic at secret/
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: mounted backend of type system at sys/
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] rollback: starting rollback manager
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: post-unseal setup complete
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: root token generated
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: pre-seal teardown starting
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] rollback: stopping rollback manager
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: pre-seal teardown complete
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: vault is unsealed
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: post-unseal setup starting
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: mounted backend of type generic at secret/
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: mounted backend of type system at sys/
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] rollback: starting rollback manager
5/17/2016 7:45:46 AM2016/05/17 11:45:46 [INFO] core: post-unseal setup complete
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AM    export VAULT_ADDR='http://0.0.0.0:8200'
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AMThe unseal key and root token are reproduced below in case you
5/17/2016 7:45:46 AMwant to seal/unseal the Vault or play with authentication.
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AMUnseal Key: 725a8914f9b2420cf3976e4a6843b8bee7168e98f15f4c760a3d1cb627cfde80
5/17/2016 7:45:46 AMRoot Token: abracadabra
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AM==> Vault server configuration:
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AM         Log Level: info
5/17/2016 7:45:46 AM             Mlock: supported: true, enabled: false
5/17/2016 7:45:46 AM           Backend: inmem
5/17/2016 7:45:46 AM        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
5/17/2016 7:45:46 AM           Version: Vault v0.5.2
5/17/2016 7:45:46 AM
5/17/2016 7:45:46 AM==> Vault server started! Log data will stream in below:
5/17/2016 7:45:46 AM
```

Is there any way to turn on a "debug" or "verbose" mode to get more information on what is happening?  Also, can you please take a look at my setting below to see if I'm off the mark?

Thanks...Dan

**Settings Used**

Rancher configured with two environments named "Rancher" and "Test".  secrets-bridge-server is deployed to Rancher and secrets-bridge-agent is deployed to Test.  A simple alpine image that runs an interactive bash shell is started to test getting the temp secret in /tmp/secrets folder.  

Alpine Compose File:
```
alpine:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: 'true'
  tty: true
  entrypoint:
  - /bin/sh
  image: alpine:3.3
```

Vault server installed and started on to same host used in Rancher environment with:
`vault server -dev -dev-root-token-id=abracadabra -dev-listen-address=0.0.0.0:8200`

Vault configured using script:
```
export VAULT_ADDR=http://xxx.xxx.xxx.xxx:8200
export VAULT_ADDR=$VAULT_ADDR
export ROOT_TOKEN=abracadabra

# Create policies for roles and applications
vault policy-write grantor-Rancher ./policies/grantor-Rancher.hcl
vault policy-write test-alpine ./policies/test-alpine.hcl

# Create role and assign policies
curl -s -X POST -H "X-Vault-Token: ${ROOT_TOKEN}" -d '{"allowed_policies": "default,grantor-Rancher,test-alpine"}' ${VAULT_ADDR}/v1/auth/token/roles/grantor-Rancher

# Assign policies to applications
vault write secret/secrets-bridge/Rancher/Test/alpine/alpine policies=test-alpine,default

# Create temporary grantor token (ttl is only 15 min)
TEMP_TOKEN=$(curl -s -H "X-Vault-Token: $ROOT_TOKEN" ${VAULT_ADDR}/v1/auth/token/create -d '{"policies": ["default"], "ttl": "24h", "num_uses": 30}'|jq -r '.auth.client_token')
PERM_TOKEN=$(curl -s -X POST -H "X-Vault-Token: $ROOT_TOKEN" ${VAULT_ADDR}/v1/auth/token/create/grantor-Rancher -d '{"policies": ["default", "grantor-Rancher", "test-alpine"], "ttl": "72h", "meta": {"configPath": "secret/secrets-bridge/Rancher"}}' | jq -r '.auth.client_token')
curl -X POST -H "X-Vault-Token: ${TEMP_TOKEN}" ${VAULT_ADDR}/v1/cubbyhole/Rancher -d "{\"permKey\": \"${PERM_TOKEN}\"}"
echo "${TEMP_TOKEN}"
```

**Comment by cloudnautique** [comment]
This is my fault, sorry :-\

This is setup to work, counter to the instructions and what I would recommend, with server and agent in the same environment where the agent is using the container IP of the Server service. I need to make it so that it exposes a port on the bridge and then the Host IP:port would be used for the agent --bridge-url setting.

If you want to play with this you'll need to launch the server in the same env as the agents. When you launch the agent, use `http://<server_container_ip>:8181`. You can get the server container Ip from the infrastructure tab. Its the 10.42.x.x address.

I'll provide an update that exposes a port for the server so it can be run in split environments in the next day or so.

**Comment by dsvmacdonald** [comment]
I cloned the catalog and updated the secrets-bridge-server to expose port 8181 and retried.  A definite connection was made as I see more info in the logs...but I ran into another problem.  The verified object is missing all the rancher metadata (serviceName, stackName...).  Here are the bridge-server logs:
```
5/17/2016 4:13:38 PMtime="2016-05-17T20:13:38Z" level=info msg="Listening on port: 8181"
5/17/2016 4:15:49 PMtime="2016-05-17T20:15:49Z" level=info msg="Verifing: ab7f9d18-3775-492c-920b-db38618d8724"
5/17/2016 4:16:52 PMtime="2016-05-17T20:16:52Z" level=info msg="VerifiedObj: &verifier.RancherVerifiedResponse{verified:false, serviceName:\"\", stackName:\"\", containerName:\"\", environmentName:\"\", id:\"\"}"
5/17/2016 4:16:52 PMtime="2016-05-17T20:16:52Z" level=info msg="VerifiedObj Path: ///"
5/17/2016 4:16:52 PMtime="2016-05-17T20:16:52Z" level=info msg="VerifiedObj ID: "
```

Thoughts?  I'll try running all locally now.

**Comment by cloudnautique** [comment]
I think that happens when its just a single container not launched as a stack is detected. But, I could be wrong =D  If you got that far, it means everything can connect. 

Based on your setup of vault, you will only get keys for things deployed in the Test environment, alpine stack, alpine service so something like:

```
# docker-compose.yml
alpine:
  image: alpine

# Rancher command
rancher-compose -p alpine up -d

where RANCHER_URL=http://rancher/v1/projects/1aX where 1aX id is associated name==Test.

```

The Rancher api keys are a bit weird, since they are for the environment where the Agents will run, not where the server will run. The server will only have access to a single environments containers.

**Comment by dsvmacdonald** [comment]
I'm not running containers outside of a stack.  I shutdown everything and restarted...that error went away.  Now I'm getting:
```
5/17/2016 4:48:54 PMtime="2016-05-17T20:48:54Z" level=info msg="Verifing: 98250d6f-34af-42b5-a4ff-9ccf574e9f29"
5/17/2016 4:48:55 PMtime="2016-05-17T20:48:55Z" level=info msg="Getting Temp Token"
5/17/2016 4:48:55 PMtime="2016-05-17T20:48:55Z" level=error msg="Error making API request.\n\nURL: POST http://159.203.72.2:8200/v1/auth/token/create/grantor-Rancher\nCode: 403. Errors:\n\n* permission denied"
5/17/2016 4:48:55 PMtime="2016-05-17T20:48:55Z" level=error msg="Unverified: Error making API request.\n\nURL: POST http://159.203.72.2:8200/v1/auth/token/create/grantor-Rancher\nCode: 403. Errors:\n\n* permission denied"
```
I think I have something wrong in my configs.  When I went to a single environment, I removed the test stuff and put everything within the "Rancher" environment.  

Below are my latest configs...can you take a look at the paths below. 

But before that, I may be able to help you with the Rancher API keys issue.  This pattern definitely won't scale if you move the bridge into say an Operations environment only.  My team recently updated the Logspout catalog to add Rancher Environment, Stack and Service name to container logs so we could quickly filter by them within Kibana in our ELK stack.  The data is added to the log metadata when Logspout sees that a container has started or restarted.  It uses the Rancher Metadata Service to get this data.  I'll try and submit a pull request to the Logspout Community catalog tomorrow so you can look at the code...fyi..we're new to Go so I'm sure you have some fixes for it.

**Latest Configs**

grantor-Rancher.hcl:
```
# grantor-Rancher should not have access to sys
path "sys/*" {
  capabilities = ["deny"]
}

# Scope to rancher environment
path "secret/secrets-bridge/Rancher/*" {
  capabilities = ["read", "list"]
}

path "auth/token/create/grantor-Rancher" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Limit scope of grantor-Rancher by first denying access to all secrets
path "secret/*" {
  capabilities = ["deny"]
}
```
rancher-alpine.hcl:
```
path "sys/*" {
  capabilities = ["deny"]
}

path "secret/Rancher/Rancher/alpine" {
  capabilities = ["read", "list"]
}
```

setup.sh script:
```
export VAULT_URL=http://xxx.xxx.xxx.xxx:8200
export VAULT_ADDR=$VAULT_URL
export ROOT_TOKEN=abracadabra

# Create policies for roles and applications
vault policy-write grantor-Rancher ./policies/grantor-Rancher.hcl
vault policy-write rancher-alpine ./policies/rancher-alpine.hcl

# Create role and assign policies
curl -s -X POST -H "X-Vault-Token: ${ROOT_TOKEN}" -d '{"allowed_policies": "default,grantor-Rancher,rancher-alpine"}' ${VAULT_URL}/v1/auth/token/roles/grantor-Rancher

# Assign policies to applications
vault write secret/secrets-bridge/Rancher/Rancher/alpine policies=rancher-alpine,default

# Create temporary grantor token (ttl is only 15 min)
TEMP_TOKEN=$(curl -s -H "X-Vault-Token: $ROOT_TOKEN" ${VAULT_URL}/v1/auth/token/create -d '{"policies": ["default"], "ttl": "15m", "num_uses": 2}'|jq -r '.auth.client_token')
PERM_TOKEN=$(curl -s -X POST -H "X-Vault-Token: $ROOT_TOKEN" ${VAULT_URL}/v1/auth/token/create/grantor-Rancher -d '{"policies": ["default", "grantor-Rancher", "rancher-alpine"], "ttl": "72h", "meta": {"configPath": "secret/secrets-bridge/Rancher"}}' | jq -r '.auth.client_token')
curl -X POST -H "X-Vault-Token: ${TEMP_TOKEN}" ${VAULT_URL}/v1/cubbyhole/Rancher -d "{\"permKey\": \"${PERM_TOKEN}\"}"
echo "${TEMP_TOKEN}"
```

**Comment by dsvmacdonald** [comment]
Thought...if the rancher api keys are also needed to update the running container with temp secret, maybe the agent could be updated with some cowbell like functionality.

**Comment by cloudnautique** [comment]
There is an unpleasant usability tradeoff with the temp tokens done for security. When the server side is restarted... it will not be able to get a token. The temp token is no longer valid and the permanent key is lost from memory. It needs to be relaunched all together. I should add a flag that allows you to launch via permanent token if you really want. Or possibly store the issuing token. Very open to community input on this one. I should add an LB to the stack so its potentially less volatile, and you can do blue/green deploys behind it.

The agents do have have API keys, but they are only used to create signature tokens. (not currently available, but coming soon) The secrets.txt file is copied via docker commands to the Docker ID returned by a successful response.

I'm not too sure I follow on the bridge/logging bit. The bridge would still be part of an env/stack/service and could still log to Elasticsearch. The reason/fear that I'd deploy it into a separate environment is that if the hosts in an environment were compromised, they couldn't get access to both Rancher and Vault (with issuing access). This might be overkill though, thinking about it a bit more.

**Comment by dsvmacdonald** [comment]
Now I'm confused...

`There is an unpleasant usability...`
If I understand it correctly, every time the bridge-server is restarted, it needs a new temp token.  But agents and containers can be started and stopped independently of this...correct?  Or are you saying, it only works if bridge-server, bridge-agent and containers are all started at same time?

`The agents do have have API keys, but ...`
I assume that the agents don't need the keys to interact with containers in their own environment...I might be wrong, but I was really commenting on the need to add api keys for environment in which the agent runs to the bridge-server...if that was needed for some cross-environment container/docker chatter, then I was proposing to replace this with a bridge-server to bridge-agent mechanism where the server would instruct the agent to do the work...like using cowbell to scale-up a service instead of rancher-compose...maybe way off base her b/c didn't look at the code enough

`I'm not too sure I follow on the bridge/logging bit`
Nothing to do with logging per-se...originally thought the api keys were used to get container rancher data such as environment name, stack and service...and was suggesting that if this was the case to just have the agent pass this information over.  Agent could get this data from the Rancher Metadata Service as the containers start up

Any chance you looked at my new setting...2 posts ago for the permission issue I ran into?

Thx

**Comment by cloudnautique** [comment]
Sorry... 

usability... you have it. Every time bridge server restarts it needs a new temp token. Agents/stacks/containers operate independently. 

Agent Api keys...
They have keys so that we can use the private key to sign its UUID:timestamp. That will then be sent to the bridge which will be able to verify the agents identity via api call. That API call does not exist today.

Config... 
If I understood correctly, the service was restarted, and it wasn't able to get a real issuing token, so its unable to create tokens.

If you want to do a screen share, I'm really interested in getting this running, email me bill at rancher dot com.

**Comment by dsvmacdonald** [comment]
When I restarted and reran setup, the first error went away but then I got
the permission, error.  I'll email u on the screen share in 20 min

On May 17, 2016, at 6:12 PM, Bill Maxwell <notifications@github.com> wrote:

Sorry...

usability... you have it. Every time bridge server restarts it needs a new
temp token. Agents/stacks/containers operate independently.

Agent Api keys...
They have keys so that we can use the private key to sign its
UUID:timestamp. That will then be sent to the bridge which will be able to
verify the agents identity via api call. That API call does not exist today.

Config...
If I understood correctly, the service was restarted, and it wasn't able to
get a real issuing token, so its unable to create tokens.

If you want to do a screen share, I'm really interested in getting this
running, email me bill at rancher dot com.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/rancher/community-catalog/issues/146#issuecomment-219870022>

**Comment by cloudnautique** [comment]
OK, I think I have it figured out! 

It looks like the `vault policy-write grantor-Rancher ./policies/grantor.hcl` the name grantor-Rancher gets lower cased. I saw that when the permanent token is created there is a warning on the response that policy grantor-Rancher does not exist. `vault policies` showed that it had been renamed to grantor-rancher. If you change your scripts so that the policy is named grantor-rancher instead of grantor-Rancher things should work. The URL paths do not appear to follow the same behavior, they can have uppercase letters. 

Let me know if this solves it!

**Comment by dsvmacdonald** [comment]
Bill...that fixed it.  Thanks a lot for your timely help.
