### ISSUE TITLE
The  k8s catalog item MongoDB have some error in run.sh and yaml file

### ISSUE THREAD

**Issue by frank798** [rancher/community-catalog#163]
my k8s'version is:
`Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"b57e8bdc7c3871e3f6077b13c42d205ae1813fbd", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"b57e8bdc7c3871e3f6077b13c42d205ae1813fbd", GitTreeState:"clean"}`
docker version is:1.9.1
when I deploy mongoDB in k8s with yaml file.I found two error:
the first is in run.sh
`IP=$(ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1 | sed -n 2p)`
if use this script to get ip , it will return empty,but when remove `| sed -n 2p` it will be ok.

the second is in yaml file mongo-controller.yaml
in this file the environment variable PRIMARY is not set , the default value is container is true,as result,when deploy mongoDB by mongo-controller.yaml.every mongo rc instance will change to primary due to the defaule value in env.After set environment variable PRIMARY value to false,the result is correct, the member incloud one primary and 2 scendary(set replicas: 2).
so need to add PRIMARY environment variable in mongo-controller.yaml.

**Comment by Pixelartist** [comment]
I can confirm that if you launch mongodb as is (there is not much to configure anyway) .. it seems all shards are disconnected. Since I am not that deep into Rancher, I am still trying to figure out how to fix this.

**Comment by galal-hussein** [comment]
@frank798 Thanks for opening the issue, and sorry for the late reply, i am putting a fix for the problem and will release another version of the catalog very soon.

**Comment by galal-hussein** [comment]
https://github.com/rancher/community-catalog/pull/351 the PR adds a fix for the mentioned problems, also it improves the way of finding nodes, and adds persistent storage.
