### ISSUE TITLE
Missing : in volume definition in letsencrypt

### ISSUE THREAD

**Issue by EugenMayer** [rancher/community-catalog#167]
https://github.com/rancher/community-catalog/blob/master/templates/letsencrypt/2/docker-compose.yml#L23

@janeczku can you fix this in your branch and make a pullrequest?

**Comment by cloudnautique** [comment]
The description for the field say to include the colon when entering. Otherwise this will be a volume in the container.

**Comment by EugenMayer** [comment]
oh, sorry! I was to focused on the implementation i had - this makes a lot of sense to have this be configureable, i guess there is just no better way to offer it. 

I just had to read the full descriptions /me notes  to myself.

Thank you for the fast reply!

**Comment by EugenMayer** [comment]
@janeczku i think this needs better though. After testing today, i found out, that anonymous containers do not get migrated during a  catalog upgrade. So if someone leaves this option empty, he will lose all the certificates on upgrading - this is not what you want.

You should enforce a name volume or a host folder, therefore include a ":"

**Comment by janeczku** [comment]
@EugenMayer If you don't specify a volume/path in the template, the application behaves exactly like in the previous versions, that is, upon upgrading to a new version the certificate will also be renewed. Considering that LE certificates are short-lived anyways and come at zero cost i don't see this as a problem. Also, to preserve certificates during upgrades we would also need to expose the account data in the volume (which we don't at the moment). We can address this in the next version though.

**Comment by EugenMayer** [comment]
@janeczku LE certificate creation on same certificates has a threshold, this means, you cannot just create them as often as you want, just because "you lost them".

I cannot see, in any way, why this makes sense. Not allowing anon-volumes does make a lot of sense here, otherwise you risk someone is banned from LE by rerequesting certificates too often. I admin its not to be expected that you will offer a catalog update 50 times a month, so chances are low, but still, this concept has no benefits at all - just downsides.

Or do i miss something? Also do not get me wrong, it is not important for me as a person - i simply wont use those anon volumes, because i know that upgrades behave this way. I do not think a lot of people do expect upgrades to throw away the volume though.

**Comment by janeczku** [comment]
> I cannot see, in any way, why this makes sense. Not allowing anon-volumes does make a lot of sense here, otherwise you risk someone is banned from LE by rerequesting certificates too often.

An identical certificate can be (re-) issued  up to 5 times per week (https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769). The release cycle of this template is at most once per month. Hence upgrading to a newer version is not problematic at all in that regard.

I will not make creating a named volume the default. Here is why:
A named volume means that the certificate private key will persists on the host even after removing the service. This is not what most users would expect or want from a security standpoint.

The fact that the unnamed container volume is not moved over when doing a service upgrade is unexpected IMHO and should be addressed in Rancher server. If you have any suggestions how to do this differently, please open an issue in https://github.com/janeczku/rancher-letsencrypt/issues and we can continue the discussion there.
