### ISSUE TITLE
DataDog agent Host labels don't work

### ISSUE THREAD

**Issue by jmreicha** [rancher/community-catalog#190]
Just deployed the DataDog agent via the catalog entry.   I set `service:rancher,environment:rancher` for the `Host labels to DataDog tags` variable but it doesn't look the like the tags I set are being propagated to DataDog correctly.

**Comment by janeczku** [comment]
@jmreicha you need to pass just the key of the host labels, not key:value pairs.
The values will be determined automatically when the stack gets deployed since they might be different between hosts 😀

**Comment by jmreicha** [comment]
Thanks, I'll give that a try.

**Comment by jmreicha** [comment]
@janeczku Thanks it is working.  Sorry I didn't get around to this sooner.
