### ISSUE TITLE
How to link ClusterControl to Percona XtraDB Cluster

### ISSUE THREAD

**Issue by samouds** [rancher/community-catalog#214]
Hello,

I'm trying to connect CusterControl to pxc. I've installer pxc from the catalog and added ClusterControl as a new service. But the problem is when I login to ClusterControl and try to add the existing node it fails because of ssh connection :  

Can't connect (SSH): libssh connect error: Connection refused

Anyone have already tried to get the two services communicate ?

**Comment by krzysztof-ksiazek** [comment]
Hi,

I'm not sure if this will answer your question but in general ClusterControl requires password-less ssh access configured between the CC node and database nodes it manages. Please make sure you have set up the ssh keys and you can freely ssh from the ClusterControl host to your PXC using keys.
