### ISSUE TITLE
Gitlab Template doesn't start

### ISSUE THREAD

**Issue by galal-hussein** [rancher/community-catalog#239]
Rancher Version: v1.2.0-pre1

The Gitlab catalog entry doesn't start and the **gitlab_gitlab-server_1** container stopped without throwing any error in the logs.

**Comment by cdrx** [comment]
On a related note, the version of GitLab used in the template (8.5) is quite old now, current version is 8.11.

**Comment by galal-hussein** [comment]
The Issue was conflict between host and container on port 22
