### ISSUE TITLE
Traefik Template Error

### ISSUE THREAD

**Issue by galal-hussein** [rancher/community-catalog#240]
Rancher Version: v1.2.0-pre1

Trying to run the Traefik catalog template resulted in error, where no containers are being created and the state of the stack is Unhealthy.

**Comment by SantoDE** [comment]
This also happens in 1.1.2.

**Comment by MikaXII** [comment]
Because label  `traefik_lb=true` not added on the host

**Comment by rawmind0** [comment]
Hi guys...

yes, you need to set traefik_lb=true in the hosts you want to start traefik instance. 
It's an affinity rule to get control over which host runs traefik. 

It was a fixed label, but in last version you could set your own host label...

Best regards...

**Comment by galal-hussein** [comment]
@rawmind0 I still getting the same error even with the traefik_lb=true label on the host

**Comment by galal-hussein** [comment]
@rawmind0 The issue is in  io.rancher.scheduler.affinity:host_label, it was causing the containers not to start, https://github.com/rancher/rancher/issues/6163

**Comment by rawmind0** [comment]
you are right @galal-hussein... thanks so much about the info.

Best regards.....

**Comment by emcniece** [comment]
@galal-hussein any chance you could explain the solution with more detail?

**Comment by emcniece** [comment]
Got it. The `traefik_lb=true` label should be set on the host, not the stack. This has to be done for every host? Each host needs a separate instance of Traefik?

To add this label to a host:

1. Navigate to **Infrastructure** > **Hosts**
1. On the target host, click the 3 vertical dots then **Edit**
1. Add a new label, paste `traefik_lb=true`
1. Save settings, then watch the Traefik stack update

**Comment by rawmind0** [comment]
You are right @emcniece...

You have to set the host label in all the hosts you want to start traefik. It's a way to control where to deploy it. :)

In new versions, waiting PR approval, host label could be whatever you want. You could set it in deployment time.

Best regards...

**Comment by rawmind0** [comment]
Solved with this merged PR https://github.com/rancher/community-catalog/pull/300 ...
