### ISSUE TITLE
Hadoop Illegal character in host-name

### ISSUE THREAD

**Issue by JendaPlhak** [rancher/community-catalog#248]
Hi, we use rancher template for hadoop+yarn, but it seems that hadoop is unable to deal with using container names as hostnames.

`Caused by: java.net.URISyntaxException: Illegal character in hostname at index 13: http://hadoop_datanode_1:50075/webhdfs/v1/skystore/tmp/devtest_onedir/2016_08_19_02_35_35_32f7/header.json?op=CREATE&user.name=hdfs&namenoderpcaddress=10.42.14.252:8020&overwrite=true`

Am I doing it wrong or is there some workaround?

As I see it the problem is caused byt using container names as host names while rancher creates containers with underscores. Have no idea how to fix it though...

**Comment by rawmind0** [comment]
Rancher is using  now '-' intead of '_ '  in containers names. Current hadoop catalog package seems to work fine.

Please, reopen if you still have the issue.
