### ISSUE TITLE
Elasticsearch 1 and 2. kopf returns 502 bad gateway error. 

### ISSUE THREAD

**Issue by fjoesne** [rancher/community-catalog#259]
I have tried both Elasticsearch 1 and 2. 

I have not done anything to the catalog settings :

[rancher-compose.yml.txt](https://github.com/rancher/community-catalog/files/440819/rancher-compose.yml.txt)
[docker-compose.yml.txt](https://github.com/rancher/community-catalog/files/440818/docker-compose.yml.txt)

going to the kopf UI on both versions gives me an error message that [ip}:80/es returns a 502 bad gateway.  I have tried on a local hosts as well as digitalocean-droplets the result is the same. 

errorlog from elasticsearch-2_elasticsearch-clients-1: 
[log.txt](https://github.com/rancher/community-catalog/files/440824/log.txt)

**Comment by winfredSui2016** [comment]
I also met this problem,can anybody give some solution?

**Comment by rawmind0** [comment]
Current version working.

Please, reopen if you still have the issue.
