### ISSUE TITLE
[consul-registrator] continuously produces error "ip: can't find device 'eth0'"

### ISSUE THREAD

**Issue by ravlio** [rancher/community-catalog#261]
After "consul registrator" template installation one of three containters which is `consul-registrator_consul-registrator_consul_1` does not start, instead it constantly try to restart and spawn error in logs:

```
30.08.2016 12:30:41 Could not find IP for interface 'eth0', exiting
30.08.2016 12:32:28 ip: can't find device 'eth0'
```

**Comment by johnrengelman** [comment]
can you shell into one of the containers and run `ifconfig -a` and see what you have listed for interfaces?
What OS are you running on?
You could try upgrading the container and modifying this setting -https://github.com/rancher/community-catalog/blob/master/templates/consul-registrator/1/docker-compose.yml#L47

**Comment by mch1307** [comment]
Hi, got exact same issue. After playing around I found that this container is setup with "host" networking. In my case, it was not getting any IP, and therefore failing to start the agent. I changed it to "managed" and all services are now up and running

**Comment by mch1307** [comment]
my previous comment can be ignored, it cannot work like that. Instead as mentioned by @johnrengelman the network interface should be simply changed in the environment variable to the one that is available within the container. In my case, it was ens192, not eth0: Changing it to the correct net interface fixed the issue

**Comment by rawmind0** [comment]
Fixed catalog package. Added catalog variable to change bind interface.
