### ISSUE TITLE
[consul registrator] Support encryption keys

### ISSUE THREAD

**Issue by jhmartin** [rancher/community-catalog#264]
A well secured Consul environment utilizes gossip encryption (a static pre-shared key) and TLS for inter-node communication.  The catalog template does not support this.

https://www.consul.io/docs/agent/encryption.html

I am assuming here that the gossip and TLS keys would have been created externally and only need to be provided to the template.

**Comment by rawmind0** [comment]
Hi @jhmartin ...

Consul catalog template already supports gossip encryption and tls inter-node communication, as you could read at it's info section. 

Your are assuming right. You only need to create CA, certs and encryption key and provide them to the template. :)

Best regards...
