### ISSUE TITLE
gogs template: missing mysql_database_name env

### ISSUE THREAD

**Issue by fernandoneto** [rancher/community-catalog#28]
in mysql service the `MYSQL_DATABASE` env is missing. this way no databases was created. and when you try to configure gogs you get this error:

![captura de ecra de 2016-03-10 16 37 57](https://cloud.githubusercontent.com/assets/6515784/13676720/cfb4f902-e6de-11e5-9a85-10baa84273f1.png)

If you execute a shell in mysql container and list databases you will see no database was created.
![captura de ecra de 2016-03-10 16 42 11](https://cloud.githubusercontent.com/assets/6515784/13676766/0b08894c-e6df-11e5-81c5-32131c730ff2.png)
## Update

After create the database manually i was able to finish the installation process

**Comment by xinity** [comment]
oupsy ! my bad :(

i'll fix it by the end of the week

**Comment by mastertinner** [comment]
@xinity, I'm still getting this error... has it ever been fixed?

**Comment by xinity** [comment]
Pr will be made today. Sorry being so late fixing this simple issue :-(

**Comment by mastertinner** [comment]
awesome, thanks!

**Comment by RotemEmergi** [comment]
any update ?

**Comment by francoishill** [comment]
This is a **community** catalog. If you already know the fix please fix it and send a pull-request.
