### ISSUE TITLE
How to update Rancher metadata when the stack is already launched?

### ISSUE THREAD

**Issue by geeknam** [rancher/community-catalog#306]
Probably related to https://github.com/rancher/rancher/issues/2484 aka how to update rancher metadata, should it be treated as a key value store?

**Comment by rawmind0** [comment]
Hi @geeknam....

yep, you are right it's related. By the moment, it's not possible to update rancher metadata once the stack is already launched. You only be able to read, not write. 

What do you need to do?? As an alternative, you could deploy a etcd, consul, zookeeper (all in rancher catalog) to do what you may need. 

BTW, if your environment scheduler is k8s, you may use the k8s api and/or etcd to write labels, annotations or whatever you need.

**Comment by rawmind0** [comment]
Closing issue...Please follow, rancher/rancher#2484 ...
