### ISSUE TITLE
Update current version of GitLab.

### ISSUE THREAD

**Issue by blandes** [rancher/community-catalog#313]
Replace the current version of the GitLab catalog template because it's old and also modify the docker-compose.yml to use [sameersbn/docker-gitlab](https://github.com/sameersbn/docker-gitlab) approach. 

And If possible, add a catalog template for GitLab runners as well.

**Comment by ununseptium** [comment]
I think the general issue here, the "update of gitlab version" is going to be resolved if the PR #343 is merged.

**Comment by rawmind0** [comment]
Closed due to PR #343 is already merged.
