### ISSUE TITLE
Add Minio to the community-catalog

### ISSUE THREAD

**Issue by blandes** [rancher/community-catalog#314]
Nothing too crazy here. Just making a catalog template for [Minio](https://www.minio.io/) which is a minimalistic Amazon S3 compatible object storage server.

**Comment by disaster37** [comment]
Hi, I will work on this enhance

**Comment by zoidbergwill** [comment]
We're hoping to test out running this on Rancher soon. Any way I could help?

**Comment by mathieu-gilloots** [comment]
:+1:

**Comment by disaster37** [comment]
I work actively on it, i hope to do PR next week
