### ISSUE TITLE
Feature request : Mesos/Spark/Chronos

### ISSUE THREAD

**Issue by AlexisDucastel** [rancher/community-catalog#33]
Hi there,

I think it would be very interesting to have the ability to deploy a new kind of environment (like cattle or kubernetes) which would be Mesos.

It has a lot of features, and for me, the first is Spark support. Other projects built on top of Mesos are also interesting like Chronos.

Is there anyone else intetested in Mesos over Rancher ?

Thanks.

**Comment by lavvy** [comment]
+1

**Comment by sheng-liang** [comment]
Besides Apache Mesos, Spark, and Chronos, what other frameworks should be supported? Marathon? Any others?

**Comment by lavvy** [comment]
It will be nice to get openstack on rancher

**Comment by AlexisDucastel** [comment]
Marathon would be of course a very good candidate.

Openstack in rancher wouldn't  be a good solution. Openstack is a bunch of projects that are providing a private cloud solution as an IaaS. It needs very low layers like complex networking with OpenvSwitch in Neutron. If you need Openstack services with easy solution, just give a try to Openstack Fuel which is an Openstack deployment assistant.

For me, if you don't rely on a public cloud for security reasons, you will enjoy deploying an Openstack solution in house, and then deploy Rancher to manage your containers clusters.

Anyway, if you really want to implement another techno, Hadoop, and especially YARN (ZooKeeper + HDFS + YARN) would be great in rancher (but i think we're going too far away from Cattle, Kubernetes and Mesos are both containers as a services solutions, and there is already a lot of tools to manage hadoop installations.)

**Comment by AlexisDucastel** [comment]
By implementing mesos, you're opening all these projects : http://mesos.apache.org/documentation/latest/frameworks/

**Comment by claytonsilva** [comment]
+1  . 

i'm working in my catalog to develop mesos-cluster

https://github.com/gerencio/gerencio-catalog

**Comment by rawmind0** [comment]
Already implemented from v1.1....
