### ISSUE TITLE
Janitor Catalog: Volume Parameter Request

### ISSUE THREAD

**Issue by dahendel** [rancher/community-catalog#34]
Could you add a parameter for the docker volume that gets mounted? I was going to make my own, but figured I might not be the only one to use the Community catalog that has docker installed in a different location.

Thanks for the awesome entry!

**Comment by KrustyHack** [comment]
Ay,

You mean this one: "/var/lib/docker:/var/lib/docker" ?

**Comment by dahendel** [comment]
Correct.
