### ISSUE TITLE
OpenNebula Machine driver doesn't appear in v1.2.0

### ISSUE THREAD

**Issue by km4rcus** [rancher/community-catalog#357]
Thanks @galal-hussein @rawmind0 for the merge of the OpenNebula machine driver.

I noticed that the OpenNebula machine driver doesn't appear when starting the rancher server container (v1.2.0)  unless I "refresh" the community catalog by disabling and then re-enabling it from the admin settings or I pass the catalog url via the env variable DEFAULT_CATTLE_CATALOG_URL.

Furthermore, by using the latest rancher image, I noticed that in the machine drivers page the OpenNebula machine driver shows up but the logo doesn't appear.

**Comment by galal-hussein** [comment]
Thanks @km4rcus I just reproduced the problem.

@vincent99 Can you check this problem ^, the community catalog has to be refreshed in order for the machine template to appear.

**Comment by deniseschannon** [comment]
@km4rcus With 1.2.2, I see it available by default. I believe that catalogs weren't automatically refreshed in v1.2.0 and just using the cached catalog inside Rancher server. This was addressed in either 1.2.1 or 1.2.2. 

Please let me know if you still have issues.
