### ISSUE TITLE
QuasarDB category typo ?

### ISSUE THREAD

**Issue by radu-stefanache** [rancher/community-catalog#395]
Shouldn't QuasarDB be in the databases category ?
Instead is in the Database (!=Databases) category.

https://github.com/rancher/community-catalog/blob/master/templates/quasardb-community/config.yml#L5

**Comment by rawmind0** [comment]
thanks @radu-stefanache ... 

Fixed category to databases... https://github.com/rancher/community-catalog/pull/587
