### ISSUE TITLE
elasticsearch 5.x

### ISSUE THREAD

**Issue by llaine** [rancher/community-catalog#403]
Hi folks, 
I'm looking to setup a new ELK stack using Rancher, but I wondered why we only have the 2.x version in the catalog available? 
Does the 5.x version is not supported yet for this cluster stack ?

**Comment by hugodopradofernandes** [comment]
I created that to monitor all logs from containers. I don't know how to submit that to the catalog

You can go to stacks, click "add astack" and on docker-compose.yml, paste that below
Then go to kibana on port 5601
That also add a logspout on each node you have.

> version: '2'
> 
> services:
>   elasticsearch1:
>     image: elasticsearch:5
>     ports:
>       - "9200:9200"
>       - "9300:9300"
>     environment:
>       - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Des.path.conf=/usr/share/elasticsearch/config"
>       - "discovery.zen.ping.unicast.hosts=elasticsearch1"
>       - "cluster.name=elasticsearch"
>       - "network.host=0.0.0.0"
>       - "discovery.zen.minimum_master_nodes=1"
>     ulimits:
>       memlock:
>         soft: -1
>         hard: -1
>       nofile:
>         soft: 65536
>         hard: 65536
>     cap_add:
>       - IPC_LOCK
>     volumes:
>       - /usr/share/elasticsearch/data
>       - /usr/share/elasticsearch/config
>     networks:
>       - docker_elk
>     labels:
>         io.rancher.container.hostname_override: container_name
> 
>   logstash:
>     image: logstash:5
>     command: -f /etc/logstash/conf.d/ --config.string 'input { udp { port => 5000 codec => "json" } tcp { port => 6000 codec => "json" } } output { elasticsearch { hosts => "elasticsearch:9200"} }' 
>     volumes:
>       - /etc/logstash/conf.d
>     ports:
>       - "5000:5000"
>       - "6000:6000"
>     networks:
>       - docker_elk
>     depends_on:
>       - elasticsearch
>     labels:
>         io.rancher.container.hostname_override: container_name
>     links:
>       - elasticsearch1:elasticsearch
> 
>   kibana:
>     image: kibana:5
>     volumes:
>       - /etc/kibana/
>     environment:
>         SERVER_PORT: "5601"
>         SERVER_HOST: "0.0.0.0"
>         ELASTICSEARCH_URL: "http://elasticsearch:9200"
>     ports:
>       - "5601:5601"
>     networks:
>       - docker_elk
>     depends_on:
>       - elasticsearch
>     labels:
>         io.rancher.container.hostname_override: container_name
>     links:
>       - elasticsearch1:elasticsearch
> 
>   logspout:
>     environment:
>         ROUTE_URIS: "logstash+tcp://logstash:6000"
>         LOGSPOUT: 'ignore'
>     volumes:
>       - '/var/run/docker.sock:/var/run/docker.sock'
>     links:
>       - logstash:logstash
>     labels:
>         io.rancher.scheduler.global: 'true'
>         io.rancher.container.hostname_override: container_name
>     tty: true
>     image: bekt/logspout-logstash:latest
>     stdin_open: true
> 
> networks:
>   docker_elk:
>     driver: bridge

**Comment by junkiebev** [comment]
I have a rancher catalog item based on the above docker-compose file which anyone can use as a starting point for making an actual catalog item. I am dim and lack worth so DO NOT TRUST IT FOR PRODUCTION! This catalog item is as basic as can be - it doesn't even have sidekicks yet.

- I'm only sure(ish) that version 5.1.2-rancher3 will actually deploy at all - anything else is a work in progress
- AGAIN, DO NOT USE THIS IN PRODUCTION!
- Furthermore, I wouldn't trust anything in that catalog at all for production use!
- It would be sweet if someone would make a non-scrub version with confd <:-]

Here is the URL to add as a a custom catalog if you want https://github.com/junkiebev/community-catalog.git

**Comment by rawmind0** [comment]
Elasticsearch 5.X is already added to the community catalog, https://github.com/rancher/community-catalog/pull/583
