### ISSUE TITLE
Sentry Catalog

### ISSUE THREAD

**Issue by wahmedswl** [rancher/community-catalog#404]
Hi,
   It seems like sentry_email_password has been duplicated with types: password & string.

https://github.com/rancher/community-catalog/blob/master/templates/sentry/0/rancher-compose.yml#L49

https://github.com/rancher/community-catalog/blob/master/templates/sentry/0/rancher-compose.yml#L55

Also, will it  be possible to update this to latest version?

Thanks

**Comment by rawmind0** [comment]
Solved with https://github.com/rancher/community-catalog/pull/544
