### ISSUE TITLE
Using helm charts for k8s?

### ISSUE THREAD

**Issue by pierreozoux** [rancher/community-catalog#433]
Just a quick question, wouldn't it make more sense to use helm charts to deploy application to k8s?

**Comment by cloudnautique** [comment]
Since Rancher 1.3, we have been deploying Tiller for you in our k8s environment. In Rancher 1.4 Helm is the only catalog available to you. It is still command line based though. Long story short, you can use Helm out of the box!

**Comment by moshe0076** [comment]
Hi,
Thanks for adding Tiller as part of the deployment!
Just one question to be sure: If I upgrade the Tiller version will it impact Rancher in any way? 

Thanks again,
Moshe.
