### ISSUE TITLE
Add cloud.ca Docker Machine & Rancher UI drivers

### ISSUE THREAD

**Issue by prollynomial** [rancher/community-catalog#491]
Now that we've developed Docker Machine and Rancher UI drivers for cloud.ca, we want to get them into the community catalog so that it's easier for our customers to get started with our Rancher integration.

PR: #482

If there's anything missing or incorrect in the PR, please let me know!

**Comment by rawmind0** [comment]
Sorry for the delay @prollynomial ...

Already merged https://github.com/rancher/community-catalog/pull/482
