### ISSUE TITLE
Cloudflare Service missing service_name

### ISSUE THREAD

**Issue by pmalsenz** [rancher/community-catalog#502]
Hi all,

today I was setting up a new server, which is running Ubuntu 16.04 and Rancher Server v1.6.0, together with Docker CE 17.03 and everything is running fine so far, except the Cloudflare external DNS stack.

As I created a new environment with Cloudflare as external DNS service, I've got an infrastructure stack, but the service creation failed with:

> template: template:34: function "service_name" not defined

I tried to set up Cloudflare in a user stack, but without success and the same error message.

Haven't had time today to compare the infra-templates using rancher/external-dns in detail, but as far as I remember the dnsupdate template is using v0.6.2 and cloudflare v0.6.0.

May this difference cause this error ?

Versions in detail:

Component | Version
----------------|----------
Rancher | v1.6.0
Cattle | v0.179.7
User Interface | v1.6.1
Rancher CLI | v0.6.0
Rancher Compose | v0.12.5

Regards Peter

**Comment by airdata** [comment]
I have same issue with https://github.com/rancher/community-catalog/tree/master/templates/dnsupdate-rfc2136

**Comment by rawmind0** [comment]
Hi guys,

issue solved for all external-dns providers, https://github.com/rancher/rancher-compose-executor/pull/26
