### ISSUE TITLE
Running on ports different than 443

### ISSUE THREAD

**Issue by pensiero** [rancher/community-catalog#505]
How can I run the services that use the 443 port onto another port?
Because I have a load balancer that is using the port 443 and the two load balancers conflict with each others.

Thanks

**Comment by rawmind0** [comment]
Hi @pensiero,

is your question about a concrete catalog package?? 

Anyway, you could expose services in different ports just setting the port section in the compose....
``` 
  ports:
    - "${PORT}:443"
```

If you are exposing ports through a lb, you could share the same port for different service if you configure the lb to work in layer 7. Then, you could set a host or path filter to get one service or another sharing the same exposed port. 
Please take a look at http://rancher.com/docs/rancher/v1.6/en/cattle/adding-load-balancers/ and http://rancher.com/traefik-active-load-balancer-on-rancher/

**Comment by pensiero** [comment]
I'm sorry but I don't remember at what it was referred this question. However thanks for your answer, maybe I will refer to in the future :)
