### ISSUE TITLE
Let's Encrypt:  Could not create client

### ISSUE THREAD

**Issue by haswalt** [rancher/community-catalog#510]
Simply started container from catalog entry (v0.4.0), using http verification:

```
5/19/2017 12:06:10 PMlevel=info msg="Generating private key (2048) for ***@******.***."
5/19/2017 12:06:22 PMlevel=fatal msg="LetsEncrypt client: Could not create client: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get \"https://acme-v01.api.letsencrypt.org/directory\": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
````

All other containers have network access and can make requests to external services.

**Comment by rawmind0** [comment]
Hi @haswalt ,

could you please try with upgraded let's encrypt version v0.5.0??

**Comment by haswalt** [comment]
Hi @rawmind0 

Tested with latest version as soon as it was available. Looks like it's gone away! 👍

**Comment by rawmind0** [comment]
Cool.. 👍 

Closing issue, please reopen if you have any trouble.
