### ISSUE TITLE
Synchronize community catalog with the current version of alpine-kafka

### ISSUE THREAD

**Issue by iltish** [rancher/community-catalog#520]
It would be great to synchronize community catalog with the current version of alpine-kafka repository to get the latest features.

Underlying repository ([https://github.com/rawmind0/alpine-kafka](https://github.com/rawmind0/alpine-kafka)) already has a pretty recent version (0.10.2.0) that supports time based log index.

Unfortunately community catalog still contains more outdated version that does not support it.
[https://github.com/rancher/community-catalog/tree/master/templates/kafka](https://github.com/rancher/community-catalog/tree/master/templates/kafka)

**Comment by rawmind0** [comment]
Updated rawmind0/alpine-kafka to 0.10.2.1 and synced catalog entry... :)

Best regards....
