### ISSUE TITLE
portworx breaks rancher catalog processing

### ISSUE THREAD

**Issue by gregkeys** [rancher/community-catalog#552]
portworx is causing rancher to throw the following error 

```
(Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes)
```

amazon aws rds MariaDB 10.0.17 
Rancher 1.6.2 setup with HA using 3 instances

**Comment by rawmind0** [comment]
Hi @gregkeys ,

i think this issue is not related to portworx package. This issue seems related with https://github.com/rancher/rancher/issues/9357 

Could you please take a look to your ```max_allowed_packet``` value at aws RDS service??

**Comment by rawmind0** [comment]
Closing this issue. Please reopen if you consider.
