### ISSUE TITLE
letsencrypt not updated does not support azure provider

### ISSUE THREAD

**Issue by annerajb** [rancher/community-catalog#559]
The letsencrypt version is 0.40 and there is a new one 0.50 with azure provider. 
Is there any reason for not updating to 0.50?

@janeczku

**Comment by solocommand** [comment]
@annerajb there's an existing PR for 0.50 here #507

**Comment by annerajb** [comment]
I apologize didn't saw it. I will go ahead and implement the change and update the existing PR.

**Comment by annerajb** [comment]
@solocommand is there a way to make rancher print logs when it tries to parse the community catalog?
I am trying to make it pickup the 0.5.0 change on my branch/fork but it still only shows 0.4.0

Here is my branch https://github.com/annerajb/community-catalog

**Comment by rawmind0** [comment]
@annerajb, you have a syntax error at ```https://github.com/annerajb/community-catalog/blob/master/templates/letsencrypt/4/rancher-compose.yml``` line 135, bad indented.

Otherwise, if you want to use go templating in docker-compose file, how it's the case, docker-compose file has to be called ```docker-compose.yml.tpl```

**Comment by annerajb** [comment]
Thanks, I was able to correct the typos and used docker logs to find a few more.
Should I submit a PR?

**Comment by rawmind0** [comment]
Sure... Please, open a PR once you finished. Thanks... :)

**Comment by rawmind0** [comment]
docker-compose file has to be renamed to docker-compose.yml.tpl in PR https://github.com/rancher/community-catalog/pull/577

**Comment by rawmind0** [comment]
Thanks for the PR @annerajb ...
