### ISSUE TITLE
gitlab multi runner config not found

### ISSUE THREAD

**Issue by mihai-satmarean** [rancher/community-catalog#567]
Hi, 

first Rancher, one of the greatest products I have had the chance to see in the Open Source world.

perhaps it was discussed before, did not find any reference.

We are trying to run a runner that would connect to our existing GItlab.
Started the runner in the Rancher, but the logs show continuously this line.
` Failed to load config stat /etc/gitlab-runner/config.toml: no such file or directory  builds=0`
We are using a self signed certificate for the gitlab.
Thank you!

gitlab-multi-runner"  version: "9.3.0
GitLab 9.3.2

**Comment by djskinner** [comment]
I believe the standard runner is expecting a file at that location. I've not tried it but you either have to execute shell on the container to interactively configure the runner or mount a volume to provide that configuration.

I prefer to do this configuration via environment variables, which is why I'm using this:

https://github.com/sameersbn/docker-gitlab-ci-multi-runner

It would be nicer to somehow use the official gitlab runner image whilst still being able to configure without a volume and / or manual intervention.

**Comment by rawmind0** [comment]
Hi @mihai-satmarean ,

launching gitlab-multi-runner from the catalog, execute first a sidekick ```gitlab-runner-config``` that executes the following command just to generate config file, ```/etc/gitlab-runner/config.toml```:
```
gitlab-ci-multi-runner register -n --url ${GITLAB_URL} \
  --registration-token ${GITLAB_TOKEN} --tag-list ${GITLAB_TAGS} \
  --executor docker --description Rancher Docker Runner \
  --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
  --docker-image docker:latest --docker-privileged
```

As @djskinner comments , this file is shared with the ```gitlab-runner```  service container through a docker volume.

```gitlab/gitlab-runner``` container suposse, you already have a working config file.

More than happy to merge a PR with this changes @djskinner  :)

**Comment by mihai-satmarean** [comment]
Hi,

just back from holiday, this seems like an alien language :)
I went in there and executed this in the shell of a running multi-runner
container.
Is that what I was supposed to do? I think not because is not working, and
now in the nice status line for the whole service I have this:

gitlab-runner
<http://eu-mun-ntf001:8081/env/1a5/apps/stacks/1st10/services/1s17?which=all>
 + 1 Sidekick (Expected state running but got stopped: Error response from
daemon: shim error: chmod /dev/pts/3: no such file or directory)

Thanks!

2017-08-01 14:48 GMT+02:00 Raúl Sánchez <notifications@github.com>:

**Comment by rawmind0** [comment]
Hi @mihai-satmarean ...welcome from holidays..... 

Is the ```gitlab-runner-config``` executed fine?? It has to generate ```gitlab-runner``` config... The error that you attach seems more a docker daemon issue, please review it...I've tested again the catalog package and it seems to work fine..

**Comment by rawmind0** [comment]
Hi @mihai-satmarean ...welcome from holidays..... 

Is the ```gitlab-runner-config``` executed fine?? It has to generate ```gitlab-runner``` config... The error that you attach seems more a docker daemon issue, please review it...I've tested again the catalog package and it seems to work fine..

**Comment by mihai-satmarean** [comment]
Hi, it was docker thing.
I had upgraded Rancher and the agents and everything seems fine now.
I was even able to register to a http gitlab server , still I have problems with self signed certificates.
Any hint there, something that just works? I am looking at this to get the certificates:
`openssl s_client -connect $domain:443 -servername $domain 2> /dev/null < /dev/null | openssl x509 > /etc/gitlab-runner/certs/$domain`
and after that 


`gitlab-ci-multi-runner register -n --url $domain --registration-token redactedtoken --tag-list dev --executor
 docker --description 'Rancher Docker Runner' --docker-image docker:latest --doc
ker-volumes /var/run/docker.sock:/var/run/docker.sock --docker-privileged --tls-
ca-file /etc/gitlab-runner/certs/$domain.crt`

I always get this error:
`x509: certificate signed by unknown authority
PANIC: Failed to register this runner. Perhaps you are having network problems`

**Comment by mihai-satmarean** [comment]
The config.toml file is not created even if the sidekick executes the said above register command, I will close the issue since it it possible to make it work by executing the registration in the shell.

**Comment by christhomas** [comment]
I had this problem when attempting to use the alpine version of the runner. I'm not sure whether it's related to your problem specifically. But it was this exact same issue. So maybe if you are also using the alpine version of the runner, you can swap to the other version and see if that helps?
