### ISSUE TITLE
Let's Encrypt DNS Resolvers not in docker-compose

### ISSUE THREAD

**Issue by willseward** [rancher/community-catalog#579]
lets-encrypt: v0.5.0

https://github.com/janeczku/rancher-letsencrypt/commit/e44c644d43d85c0a0d36b5f917d6e8bacba1f52f#diff-05a3aa0ab9e5687ff167e0ef3ae4c5a6R51

It looks like the `DNS_RESOLVERS` env var got left out of the docker-compose template.

@janeczku Am I missing something?

**Comment by rawmind0** [comment]
HI @willseward ...

You are right, DNS_RESOLVERS variable is missing at docker-compose definition. 
Added at PR https://github.com/rancher/community-catalog/pull/585

Thanks for the advise
