### ISSUE TITLE
Prometheus v5 data volume mismatch (no data persistence)

### ISSUE THREAD

**Issue by zanchin** [rancher/community-catalog#580]
v5 of the catalog has the following config:
```
command:  ...  -storage.local.path=/prometheus ...
volumes:
 - /data/
```

So `/data` is being mounted as a volume, but all data is being stored in `/prometheus`, which means that Prometheus as it ships does not persist it's data!

**Comment by rawmind0** [comment]
Thanks @zanchin .. 

Merged PR, closing issue.
