### ISSUE TITLE
Github admin user deleted

### ISSUE THREAD

**Issue by ThomasVD88** [rancher/community-catalog#641]
Hi,

Our github admin user got deleted.
Because of that im locked out of rancher (docker).

Is there a default admin user i can use to login or access the API to disable Access Control?
Is there another solution?

This is a very urgent issue for us and are in need for help.

kind regards

**Comment by vincent99** [comment]
http://rancher.com/docs/rancher/v1.6/en/faqs/troubleshooting/#authentication
