### ISSUE TITLE
Netdata

### ISSUE THREAD

**Issue by dmnc-net** [rancher/community-catalog#667]
I've installed Netdata from the community catalog and because image is from `titpetric/netdata` but I'd like to have official `firehol/netdata`, I'm trying to delete it.

Maybe this issue is related to rancher/rancher but I'm not able to stop and delete Netdata container
- it started again itself after I've stopped it
- it installed again (a new one) after I've deleted it

I'm new in Docker/Rancher so please what am I doing wrong?

_Rancher 1.6.10 on RancherOS 1.1.0_

**Comment by dmnc-net** [comment]
One more question, will Netdata show all from the RancherOS, not just isolated enviroment of the container, right?

**Comment by superseb** [comment]
You have to delete the stack, not the container, as the service will make sure a container is running. Yes, seems to be reading the `/proc` filesystem which is mounted into the container.

**Comment by dmnc-net** [comment]
@superseb Thanks, I realized it (and I didn't refresh the page when I was editing my issue) 
... anyway, first point, any chance to switch this community catalog item from `titpetric/netdata` to `firehol/netdata` which is up-to-date and probably from the NetData author himself? Thanks
