### ISSUE TITLE
taigafront fails to start

### ISSUE THREAD

**Issue by ColtonProvias** [rancher/community-catalog#7]
Trying to start taiga gives the following error from the taigafront container.

```
2/24/2016 3:23:32 PM2016/02/24 20:23:32 [emerg] 10#10: host not found in upstream "taiga-back" in /etc/nginx/conf.d/default.conf:25
2/24/2016 3:23:32 PMnginx: [emerg] host not found in upstream "taiga-back" in /etc/nginx/conf.d/default.conf:25
```

I did have to change the ports used as the server I am deploying on already has those ports allocated.

**Comment by ColtonProvias** [comment]
Just attempted again without altering anything; just deploying as is.  The exact same error is encountered.

**Comment by rawmind0** [comment]
Solved with that merged PR https://github.com/rancher/community-catalog/pull/242
