### ISSUE TITLE
Can't console-login to last version 1.1.1-1 of the Harbor Registry.

### ISSUE THREAD

**Issue by risayew** [rancher/community-catalog#707]
docker login 10.8.0.1:80
Username: admin
Password: 
Error response from daemon: Get http://10.8.0.1:80/v2/: Get http://10.8.0.1./service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp: lookup 10.8.0.1.: no such host (Pay attention on the last dot after ip)

See in the docker-compose       
- HARBORHOSTNAME=${harborhostname}.${traefikdomain}

${traefikdomain} will be not set.

**Comment by SDLyu** [comment]
I have same issue, how to set `${traefikdomain}`?

**Comment by risayew** [comment]
i have simply made my own catalog and added the harbor template without ${traefikdomain}.

**Comment by paulobezerr** [comment]
https://github.com/rancher/community-catalog/pull/769

Fixed traefixdomain.
