### ISSUE TITLE
RabbitMQ

### ISSUE THREAD

**Issue by virus2016** [rancher/community-catalog#83]
Hi guys,

I'm wondering if anyone has a catalog item for RabbitMQ?

Cheers,

**Comment by ColtonProvias** [comment]
There isn't one yet, but RabbitMQ is really easy to setup.  The image you are looking for is `rabbitmq:latest`.  Set the hostname to a FQDN.  Username and password default to `guest` but can be changed by setting the environment variables `RABBITMQ_DEFAULT_USER` and `RABBITMQ_DEFAULT_PASS`.  The ports are 4369, 5671, 5672, and 25672.  And the volume you will want to mount is `/var/lib/rabbitmq`.

If you want to use the web-based management interface, use the `rabbitmq:management` image instead and also expose port 15672.

**Comment by virus2016** [comment]
Yep, setup my cluster last night. It seems to be working well. Only issue is the scaling as you have to expose the 5672 port on all the instances.

**Comment by ddmng** [comment]
You could avoid to expose any port and use a Load Balancer on top.

**Comment by ddmng** [comment]
I've submitted the PR #125 that should provide a cluster-ready RabbitMQ Rancher stack. If you're still interested you could test it and report me any problems.

**Comment by virus2016** [comment]
Cool! Will do!
On 17 May 2016, at 16:40, ddmng <notifications@github.com<mailto:notifications@github.com>> wrote:


I've submitted the PR #125<https://github.com/rancher/community-catalog/pull/125> that should provide a cluster-ready RabbitMQ Rancher stack. If you're still interested you could test it and report me any problems.

**Comment by ddmng** [comment]
Just added #280 too with cluster autoheal and more parameters.
