### ISSUE TITLE
How to use this catalog in Rancher/Rancher 2.x?

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/community-catalog#835]
Adding this catalog URL in Rancher results in no new templates. Am I missing something? The default Rancher, and Kubernetes catalogs work fine. 

**Settings:**
**Name**: Community
**Catalog URL**: https://github.com/rancher/community-catalog
**Branch**: Master
**Scope**: Global

**Logs:**
2019/03/14 02:17:58 [INFO] Updating global catalog community
2019/03/14 02:17:58 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted

**Comment by rawmind0** [comment]
@gabrielcalderon, this catalog can't be used in rancher 2.x. Just helm charts repos could be used on rancher 2.x.

**Comment by gabrielcalderon** [comment]
@rawmind0 Thanks!

**Comment by rchaud** [comment]
I guess the documentation is them wrong?????
https://rancher.com/docs/rancher/v2.x/en/helm-charts/legacy-catalogs/creating-apps/
