### ISSUE TITLE
galera-lb never start....  Initializing...

### ISSUE THREAD

**Issue by corentin59** [rancher/community-catalog#97]
Hi,

When I start galera on last (and previous) version of rancher, the load balancer never finish to startup.

> 5/4/2016 15:43:15INFO: ROOT -> ./
5/4/2016 15:43:15INFO: ROOT -> ./etc/
5/4/2016 15:43:15INFO: ROOT -> ./etc/monit/
5/4/2016 15:43:15INFO: ROOT -> ./etc/monit/conf.d/
5/4/2016 15:43:15INFO: ROOT -> ./etc/monit/conf.d/haproxy
5/4/2016 15:43:15INFO: ROOT -> ./etc/default/
5/4/2016 15:43:15INFO: ROOT -> ./etc/default/haproxy
5/4/2016 15:43:15INFO: ROOT -> ./etc/haproxy/
5/4/2016 15:43:15INFO: ROOT -> ./etc/haproxy/certs/
5/4/2016 15:43:15INFO: ROOT -> ./etc/haproxy/certs/certs.pem
5/4/2016 15:43:15INFO: ROOT -> ./etc/haproxy/certs/default.pem
5/4/2016 15:43:15INFO: ROOT -> ./etc/haproxy/haproxy.cfg
5/4/2016 15:43:15INFO: Sending haproxy applied 3-a5eac3965952846cbd39c610ae44d58f5b54450bd46bdfba35c57dda8edfaab0
5/4/2016 15:43:15INFO: HOME -> ./
5/4/2016 15:43:15INFO: HOME -> ./etc/
5/4/2016 15:43:15INFO: HOME -> ./etc/cattle/
5/4/2016 15:43:15INFO: HOME -> ./etc/cattle/startup-env
5/4/2016 15:43:15INFO: ROOT -> ./
5/4/2016 15:43:15INFO: ROOT -> ./etc/
5/4/2016 15:43:15INFO: ROOT -> ./etc/init.d/
5/4/2016 15:43:15INFO: ROOT -> ./etc/init.d/agent-instance-startup
5/4/2016 15:43:15INFO: Sending agent-instance-startup applied 1-b4c20a4067550042bc08dbf6a1eea1b4687dff4ec952bbe7dde04e79dd29d15e
5/4/2016 15:43:15monit: generated unique Monit id 6fe3b6a025aeca46f989b25ddab66bb1 and stored to '/var/lib/monit/id'
5/4/2016 15:43:15Starting monit daemon with http interface at [localhost:2812]

![image](https://cloud.githubusercontent.com/assets/2035983/14284504/24e4c27c-fb48-11e5-94db-b9579148c927.png)

Any idea ?

**Comment by corentin59** [comment]
It's not a problem. network rules not correctly set. sorry

**Comment by helmo** [comment]
Just ran into the same problem... 
I'm not sure though what to fix network rules to fix...

Looks related to https://github.com/rancher/rancher/issues/5584
