### ISSUE TITLE
Cannot scale clients to Elasticsearch 2.x stack

### ISSUE THREAD

**Issue by ddmng** [rancher/community-catalog#98]
I'm trying to scale out the Elasticsearch 2.x stack provided in Rancher 1.0. Starting from a clean deployment of the stack, I used the "Scale" tool in elasticsearch-clients service. This created a new separate client that has not joined the existing client.
I can see the second client alive because kopf started switching from one client the the other every two seconds.
Is there a way to setup a cluster using this stack or I have to create a custom one?
Thanks

**Comment by andyshinn** [comment]
What I am noticing is that the `/usr/share/elasticsearch/config` isn't getting updated with the generated configuration from the confd sidekick. I'll investigate a bit more... maybe volumes_from isn't being used the same way as the 1.x template?

**Comment by andyshinn** [comment]
OK, there seems to be two issues at play here:

* The `docker-compose.yml` for 2.x has a `volume` for `/usr/share/elasticsearch/config` which seems to take precedence over `volumes_from`? I didn't think this was correct. But the config shows up correctly from the confd container after removing this volume and relying just on `volumes_from`.
* [Elasticsearch 2.x seems to die if `scripts.path` isn't an actual folder](https://github.com/docker-library/docs/issues/378). By default, this is `/usr/share/elasticsearch/config/scripts`. I created this folder in the shared confd container and the Elasticsearch container finally comes up.
* The Elasticsearch 2.x containers are only listening on 127.0.0.1:9300. Below is the output from a normal working 1.x stack and then a 2.x stack. Maybe some additional configuration is needed in the confd templates.

1.x:

```
4/5/2016 2:38:56 PM[2016-04-05 19:38:56,123][WARN ][bootstrap                ] Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out. Increase RLIMIT_MEMLOCK (ulimit).
4/5/2016 2:38:56 PM[2016-04-05 19:38:56,326][INFO ][node                     ] [estest_elasticsearch-clients_1] version[1.7.3], pid[1], build[05d4530/2015-10-15T09:14:17Z]
4/5/2016 2:38:56 PM[2016-04-05 19:38:56,327][INFO ][node                     ] [estest_elasticsearch-clients_1] initializing ...
4/5/2016 2:38:56 PM[2016-04-05 19:38:56,499][INFO ][plugins                  ] [estest_elasticsearch-clients_1] loaded [], sites []
4/5/2016 2:38:59 PM[2016-04-05 19:38:59,745][INFO ][node                     ] [estest_elasticsearch-clients_1] initialized
4/5/2016 2:38:59 PM[2016-04-05 19:38:59,745][INFO ][node                     ] [estest_elasticsearch-clients_1] starting ...
4/5/2016 2:38:59 PM[2016-04-05 19:38:59,947][INFO ][transport                ] [estest_elasticsearch-clients_1] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.42.6.142:9300]}
4/5/2016 2:38:59 PM[2016-04-05 19:38:59,967][INFO ][discovery                ] [estest_elasticsearch-clients_1] es/rLrosycWS2OKtraB1vbbtA
4/5/2016 2:39:03 PM[2016-04-05 19:39:03,055][INFO ][cluster.service          ] [estest_elasticsearch-clients_1] detected_master [estest_elasticsearch-masters_1][OXvXdgJeSD22TS7QNu1Riw][estest_elasticsearch-masters_1][inet[/10.42.127.26:9300]]{data=false, master=true}, added {[estest_elasticsearch-masters_1][OXvXdgJeSD22TS7QNu1Riw][estest_elasticsearch-masters_1][inet[/10.42.127.26:9300]]{data=false, master=true},}, reason: zen-disco-receive(from master [[estest_elasticsearch-masters_1][OXvXdgJeSD22TS7QNu1Riw][estest_elasticsearch-masters_1][inet[/10.42.127.26:9300]]{data=false, master=true}])
4/5/2016 2:39:03 PM[2016-04-05 19:39:03,068][INFO ][http                     ] [estest_elasticsearch-clients_1] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.42.6.142:9200]}
4/5/2016 2:39:03 PM[2016-04-05 19:39:03,068][INFO ][node                     ] [estest_elasticsearch-clients_1] started
4/5/2016 2:39:13 PM[2016-04-05 19:39:13,930][INFO ][cluster.service          ] [estest_elasticsearch-clients_1] added {[estest_elasticsearch-datanodes_1][uG4coyT0TpWwvj4rArRMFg][estest_elasticsearch-datanodes_1][inet[/10.42.83.33:9300]]{master=false},}, reason: zen-disco-receive(from master [[estest_elasticsearch-masters_1][OXvXdgJeSD22TS7QNu1Riw][estest_elasticsearch-masters_1][inet[/10.42.127.26:9300]]{data=false, master=true}])
```

2.x:

```
4/5/2016 3:05:03 PM[2016-04-05 20:05:03,296][WARN ][bootstrap                ] Unable to lock JVM Memory: error=12,reason=Cannot allocate memory
4/5/2016 3:05:03 PM[2016-04-05 20:05:03,297][WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
4/5/2016 3:05:03 PM[2016-04-05 20:05:03,297][WARN ][bootstrap                ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
4/5/2016 3:05:03 PM[2016-04-05 20:05:03,297][WARN ][bootstrap                ] These can be adjusted by modifying /etc/security/limits.conf, for example:
4/5/2016 3:05:03 PM	# allow user 'elasticsearch' mlockall
4/5/2016 3:05:03 PM	elasticsearch soft memlock unlimited
4/5/2016 3:05:03 PM	elasticsearch hard memlock unlimited
4/5/2016 3:05:03 PM[2016-04-05 20:05:03,299][WARN ][bootstrap                ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
4/5/2016 3:05:03 PM[2016-04-05 20:05:03,629][INFO ][node                     ] [es_elasticsearch-clients_1] version[2.2.1], pid[1], build[d045fc2/2016-03-09T09:38:54Z]
4/5/2016 3:05:03 PM[2016-04-05 20:05:03,629][INFO ][node                     ] [es_elasticsearch-clients_1] initializing ...
4/5/2016 3:05:04 PM[2016-04-05 20:05:04,066][INFO ][plugins                  ] [es_elasticsearch-clients_1] modules [lang-expression, lang-groovy], plugins [], sites []
4/5/2016 3:05:06 PM[2016-04-05 20:05:06,080][INFO ][node                     ] [es_elasticsearch-clients_1] initialized
4/5/2016 3:05:06 PM[2016-04-05 20:05:06,080][INFO ][node                     ] [es_elasticsearch-clients_1] starting ...
4/5/2016 3:05:06 PM[2016-04-05 20:05:06,163][INFO ][transport                ] [es_elasticsearch-clients_1] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
4/5/2016 3:05:06 PM[2016-04-05 20:05:06,185][INFO ][discovery                ] [es_elasticsearch-clients_1] erp/RtFdHgDeSRaIVbeVg5JaYw
4/5/2016 3:05:36 PM[2016-04-05 20:05:36,185][WARN ][discovery                ] [es_elasticsearch-clients_1] waited for 30s and no initial state was set by the discovery
4/5/2016 3:05:36 PM[2016-04-05 20:05:36,194][INFO ][http                     ] [es_elasticsearch-clients_1] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
4/5/2016 3:05:36 PM[2016-04-05 20:05:36,194][INFO ][node                     ] [es_elasticsearch-clients_1] started
```

**Comment by andyshinn** [comment]
A quick hack for the network issue is to set environment variable `ES_JAVA_OPTS` to `-Des.network.host=_site_`. Not sure if this is the best solution. I'd probably opt to fix up the confd container to set `network.host` in the YAML config to the actual container IP address. Still testing...

**Comment by ppiccolo** [comment]
👍

**Comment by ddmng** [comment]
In my logs, es 2.x seems it's listening con correct IP:
```
[2016-04-06 20:34:35,898][INFO ][node                     ] [Numinus] starting ...
[2016-04-06 20:34:36,035][INFO ][transport                ] [Numinus] publish_address {10.42.20.194:9300}, bound_addresses {[::]:9300}
[2016-04-06 20:34:36,045][INFO ][discovery                ] [Numinus] elasticsearch/kXMiy6hDQ_G1qa3bzSEw6g
[2016-04-06 20:34:39,147][INFO ][cluster.service          ] [Numinus] new_master {Numinus}{kXMiy6hDQ_G1qa3bzSEw6g}{10.42.20.194}{10.42.20.194:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-04-06 20:34:39,180][INFO ][http                     ] [Numinus] publish_address {10.42.20.194:9200}, bound_addresses {[::]:9200}
[2016-04-06 20:34:39,180][INFO ][node                     ] [Numinus] started
```
and I have `network.host: 0.0.0.0`

**Comment by ddmng** [comment]
I still can't realize how to make it work :(

**Comment by ddmng** [comment]
The only way to make it work for me so far is to add unicast discovery hosts in each elasticsearch.yml. 
This requires to make another image including the modified config file. I would prefer to use the standard elastic image so I'll try to solve with some environment variable so that only the docker-compose file is affected.

**Comment by cloudnautique** [comment]
I haven't had a chance to test, but I suspect that when the /usr/share/elasticsearch/config volume was added to the data container we started overwriting the confd container. So we are not getting any configuration files from confd/metadata.

**Comment by ddmng** [comment]
Yes, but the stack will not work anyway. Any idea on what can I do to solve without creating a custom elastic image?

**Comment by cloudnautique** [comment]
PR #104 fixes a few things that were remnants from the 1.x series (and one of our first templates)

The volume export loop was breaking this, and we were over writing things that we shouldn't have. So in elasticsearch-conf:v0.5.0 the run.sh is copied from /run.sh -> /opt/rancher/bin which in this stack should be provided by the data volume. (the conf template has the volume as well incase its launched solo...)

Also, the conf template can have new values added through metadata. The idea was its easier to update rancher-compose.yml then build new images. The unicast stuff is set in the template, so if that ever changes we will need to change the base again.

**Comment by cloudnautique** [comment]
@ddmng @andyshinn let me know if you run into anything. I'm going to close this for now.

**Comment by ddmng** [comment]
@cloudnautique I did a quick test now and it works way better than my quick&dirty solution.
I'll do many more tests in the next weeks and will let you know if there's anything else.
Thanks!
